### ISSUE TITLE
。。。

### ISSUE THREAD

**Issue by AuroraDysis** [nladuo/ustb_choose_courses_system#1]
学长有兴趣可以顺便。。
https://github.com/AuroraDysis/CampusToolkit
当然现在是重构版，还很不完全，上一个版本的preview(也有几个功能不能用
http://blog.auroradysis.com/2016/02/16/%E8%B4%9D%E5%A3%B3%E7%94%9F%E6%B4%BB%E7%9B%92%E5%AD%90/

**Comment by nladuo** [comment]
你的那个我看好像是wpf写的，估计打不开，我现在不用windows系统了，主要用ubuntu和mac。这个项目是我当时没事儿的时候写着玩儿的，现在主要做后端方面的开发。

**Comment by AuroraDysis** [comment]
好吧，其实我physics的，也是写着玩玩，找点事干

**Comment by nladuo** [comment]
这样也挺好的，你是李鑫以前班的同学吗？

**Comment by AuroraDysis** [comment]
对
